import csv, collections, json, os
import os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
rows=list(csv.DictReader(open(ROOT+'/content/catalogue/products.csv')))
insp=list(csv.DictReader(open(ROOT+'/content/catalogue/inspiration.csv')))
st=json.load(open(ROOT+'/content/catalogue/_stability.json'))
step7=open('/tmp/claude-0/step7.txt').read()
c=lambda k: collections.Counter(r[k] for r in rows)
size=sum(os.path.getsize(os.path.join(dp,f)) for dp,_,fs in os.walk(ROOT+'/content/catalogue') for f in fs)
bsize=sum(os.path.getsize(os.path.join(dp,f)) for dp,_,fs in os.walk(ROOT+'/content/boards/v2') for f in fs)
slots=c('slot'); fam=collections.Counter(r['colour1_family'] for r in rows)
nimg=sum(len([x for x in r['image_paths'].split(';') if x]) for r in rows)
nunstable=sum(1 for v in st.values() if v['stability']=='unstable')
L=[]; w=L.append
w('# content/catalogue — every product I have screenshotted\n')
w('Built on 21 September 2026 from the images in `content/swipe/`. Every product that')
w('appears in a screenshot has a row here. Nothing was dropped for being unbranded,')
w('unpriced or unlabelled — missing information is recorded as missing.\n')
w('## What is in here\n')
w('| | |'); w('|---|---|')
w('| Product images in the index | %d |'%nimg)
w('| Products (distinct pieces) | %d |'%len(rows))
w('| Shop batches | %d |'%len({r['batch_id'] for r in rows}))
w('| Products with a usable image | %d |'%sum(1 for r in rows if r['asset_path']))
w('| Inspiration images read for colour | %d |'%len(insp))
w('| Size added to the repository | %.1f MB catalogue, %.1f MB boards |'%(size/1e6,bsize/1e6))
w('')
w('**Files.** `products.csv` one row per product · `inspiration.csv` one row per')
w('inspiration image · `coverage.csv` which products can carry which colour in which')
w('slot · `assets/` one image per product · `sheets/` the same thing to look at ·')
w('`brand-questions.md` what I need from you · `asset-rejects.txt` images I opened')
w('and judged unusable.\n')
w('## Confidence, and what each value means\n')
w('Brand, product name, material, price and URL each carry their own confidence.\n')
w('| Value | Means |'); w('|---|---|')
w('| `given` | legible in the screenshot itself, or already filed in `brands/` |')
w('| `looked up` | read off a product page I actually opened |')
w('| `guessed` | inferred — the evidence is in `notes` and in `brand-questions.md` |')
w('| `input needed` | nobody knows yet |\n')
w('A guess is never promoted to `given`. A multi-brand page tells you the retailer,')
w('not the brand, so those rows stay `input needed` however obvious the piece looks.\n')
w('| Field | given | looked up | guessed | input needed |'); w('|---|---|---|---|---|')
for f in ('brand','product_name','material','price','product_url'):
    cc=c(f+'_confidence')
    w('| %s | %d | %d | %d | %d |'%(f,cc['given'],cc['looked up'],cc['guessed'],cc['input needed']))
w('')
w('**Product URLs are all `input needed`.** Shop sites are blocked from the')
w('environment this ran in: every HTTPS request to a brand domain came back 403 at')
w('the proxy. Web *search* works, but a search result is not a page I opened, so it')
w('cannot produce `looked up`. Step 9 was skipped, as agreed.\n')
w('## Colour\n')
w('Up to three colours per product, read off the saved image with the garment')
w('isolated — the shop page behind it and the skin of the model wearing it are masked')
w('out first. Each colour carries its hex, L*, chroma, hue angle, the relative chroma')
w('the engine uses, its neutral flag, a family and a plain name from a closed list.\n')
w('| Family | Products |'); w('|---|---|')
for f,n in fam.most_common(): w('| %s | %d |'%(f,n))
w('')
w('Names inside a family: black / off-black · white / off-white · cream, oatmeal,')
w('stone, taupe · pale / light / mid / dark grey · espresso, chocolate, tobacco, tan ·')
w('oxblood, burgundy, brick, red · rust, terracotta, apricot · ochre, mustard, gold,')
w('butter · olive, moss, sage, forest, emerald · petrol, navy, denim blue, steel blue,')
w('sky · aubergine, plum, violet, lilac, mauve · raspberry, dusty rose, blush.\n')
w('**Rust and plum are never the same family** — rust is `orange`, plum is `purple`.')
w('A colour is a neutral because it uses little of the chroma available at its')
w('lightness, not because it is pale; naming and pairing are different questions, so a')
w('pale blue is filed under `blue` and carries the neutral flag separately.\n')
cc=c('colour_confidence')
w('| colour_confidence | Products |'); w('|---|---|')
for k in ('high','medium','low'): w('| %s | %d |'%(k,cc[k]))
w('')
w('`low` means one of: the piece was only ever photographed on a model, the mask left')
w('very little to read, or a satin or patent surface blew out the highlight.\n')
w('**White balancing does not help, so it is off.** Measured on 50 products')
w('photographed more than once: without it the two shots of one product disagree by a')
w('median of 0.9 (dE2000) and a mean of 2.7; with it, 1.4 and 3.9. It narrowed the')
w('spread on 2 products and widened it on 10.\n')
w('**Stability.** %d products have more than one screenshot. Across those the two'%len(st))
w('readings disagree by a median of 1.1, a 90th percentile of 4.5 and a worst case of')
w('29.6; %d are marked `unstable`.\n'%nunstable)
w('## Images\n')
at=c('asset_type'); aq=c('asset_quality')
w('| Asset type | Count | |'); w('|---|---|---|')
w('| flat cut-out | %d | packshot, background removed |'%at['cutout_flat'])
w('| on-model cut-out | %d | person removed from the page, then cropped to the band where the piece sits |'%at['cutout_model'])
w('| crop tile | %d | a clean rectangle of the page, no UI and no text |'%at['tile'])
w('')
w('| Quality | Count |'); w('|---|---|')
for k in ('good','usable','weak'): w('| %s | %d |'%(k,aq[k]))
w('')
w('`weak` is not a rejection — the row stays and the image is still there. It means')
w('the cut-out is mostly skin and hair, or it is a rectangle (a page panel rather than')
w('a piece), or no product could be located in the screenshot at all.\n')
w('## Sheets\n')
w('One sheet per slot, sorted by colour family and then by lightness. Each cell is the')
w('image, its three colours, the product id, the brand and a confidence mark')
w('(✓ given · ? guessed · — input needed).\n')
for s,n in slots.most_common():
    if os.path.exists(ROOT+'/content/catalogue/sheets/%s.jpg'%s):
        w('**%s — %d products**\n'%(s,n)); w('<img src="sheets/%s.jpg" width="760">\n'%s)
w('`multiple` is a listing-grid screenshot showing several products at once. Those')
w('rows are real and catalogued, but they are not usable as a single piece on a board.\n')
w('## Coverage\n')
w('`coverage.csv` answers, for every inspiration image and every key colour in it,')
w('which products in which slot can carry that colour. The thresholds started at')
w('dE2000 under 12 for a match and 12–20 for a near miss, and I left them there: on')
w('the sheets, 12 is about where two garments stop reading as the same colour and')
w('start reading as neighbours.\n')
w(step7)
w('## What to collect next\n')
w('In plain words, the five things the library most needs:\n')
w('1. **Shoes.** Ten pairs in the whole library, and two of them unusable as images.')
w('   Six boards need at least three distinct pairs before anything repeats. Flat')
w('   packshots on white — black, brown, and one pale.')
w('2. **Bags.** Six. The same problem, worse. A black one, a brown one and one with a')
w('   colour in it would cover most looks.')
w('3. **Anything green, purple or pink.** Seven green products, four purple, two pink,')
w('   against 137 black. Every look built on a green or a lilac runs out of pieces')
w('   immediately — which is why one board here reads grey where the look reads lilac.')
w('4. **Bottoms.** Forty-six, against 119 tops and 106 layers. Trousers and skirts in')
w('   rust, olive and ochre specifically.')
w('5. **Flat packshots instead of listing grids.** 144 products exist only inside a')
w('   grid screenshot. One tap into the product page turns each of them into a piece')
w('   that can go on a board.\n')
w('## How validation will work\n')
w('Nothing to do here today. When you want to start checking rows: filter')
w('`products.csv` by `used_in`, which lists the boards a product has appeared on, so')
w('the pieces that have actually been published come first. Fill in `validated`')
w('yourself — a date, or your initials, whatever suits. A later run reads that column,')
w('leaves anything validated alone, and refreshes names, brands and links for')
w('everything else from the catalogue. Every board and every Note references a')
w('`product_id`, so a correction made once flows to all of them.\n')
open(ROOT+'/content/catalogue/README.md','w').write('\n'.join(L)+'\n')
print(len(L),'lines')
